// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID          uuid.UUID
	Name        string
	Bio         sql.NullString
	Email       string
	DateOfBirth sql.NullTime
}
