// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (int32, error)
	DeleteAuthor(ctx context.Context, id int32) error
	GetAuthor(ctx context.Context, id int32) (Author, error)
	GetAuthorsByBirthdateRange(ctx context.Context, arg GetAuthorsByBirthdateRangeParams) ([]Author, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error
}

var _ Querier = (*Queries)(nil)
